import type { Metadata } from "next";
import { Rowdies } from "next/font/google";
import "./globals.css";

const rowdies = Rowdies({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata: Metadata = {
  title: "Mormor och jag",
  description: "Generated by Hannes Alexandersson",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rowdies.className}>{children}</body>
    </html>
  );
}
